//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player
    {
        public int PlayerID { get; set; }
        [Display(Name = "Team")]
        [Required(ErrorMessage = "This field is required.")]
        public int CountryID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Player full name")]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "The name must be 4 to 50 characters long.")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "The field can only contain letters. The name must start with a capital letter.")]
        public string PlayerFullName { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Position { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Range(15, 99, ErrorMessage = "The minimum age is 15 years.")]       
        public int Age { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Club { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
