//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int Id { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "The field can only contain letters. The name must start with a capital letter.")]
        [StringLength(25, MinimumLength = 8, ErrorMessage = "Password must be between 4 and 25 characters long.")]
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Login")]
        public string UserName { get; set; }
        public string Email { get; set; }
        [StringLength(25, MinimumLength = 8, ErrorMessage = "Password must be between 4 and 30 characters long.")]
        [Required(ErrorMessage = "This field is required.")]
        public string Password { get; set; }
        public int Status { get; set; }
    }
}
